[colors.primary]
background = "#161616"
foreground = "#f4f4f4"
dim_foreground = "#f4f4f4"
bright_foreground = "#f4f4f4"

[colors.cursor]
text = "#161616"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#161616"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#161616"
background = "#c6c6c6"

[colors.search.focused_match]
foreground = "#161616"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#161616"
background = "#c6c6c6"

[colors.hints.start]
foreground = "#161616"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#161616"
background = "#c6c6c6"

[colors.selection]
text = "#161616"
background = "#F5E0DC"

[colors.normal]
black = "#393939"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#e0e0e0"

[colors.bright]
black = "#525252"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#c6c6c6"

[colors.dim]
black = "#393939"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#e0e0e0"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"
